### ISSUE TITLE
failed to run ./install

### ISSUE THREAD

**Issue by bi-kai** [mpv-player/mpv-build#127]
when I run `./rebuild -j8` , got error:
```
+ scripts/mpv-bootstrap                                           
Downloading https://waf.io/waf-2.0.9...                           
Download failed.                                                  
Downloading http://www.freehackers.org/~tnagy/release/waf-2.0.9...
Download failed.                                                  
Could not download waf-2.0.9.                                     
```

download waf-2.0.9 from official site manually, move it into ./mpv dir. then i got this error:
```
[root@lfgp000809336 mpv-build-master]# ./install          
The project was not configured: run "waf configure" first!
```

run `waf configure`, seems ok, but still got the above error.
any advise?

**Comment by CounterPillow** [comment]
>run `waf configure`, seems ok, but still got the above error.

If you really did run `waf configure` instead of `./waf configure` then you've configured with system waf instead of waf-2.0.9, which will not work.

Instead of manually trying to configure and build, just run`./rebuild` again. I'm not sure why it failed downloading waf for you, considering it literally tries the official site you also used.

**Comment by Dudemanguy** [comment]
waf support no longer exists so closing.
