### ISSUE TITLE
osc controller is not found

### ISSUE THREAD

**Issue by phanirithvij** [mpv-player/mpv-build#133]
After I build mpv using this.

```
mpv --osc=yes file
```
gives

```shell
[cplayer] Command line options: '../../../../../Videos/fun/nun_ricardo.mp4' '-v' '--osc=yes'
[cplayer] mpv 0.32.0-494-gbd911efdcd Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
[cplayer]  built on Tue May 19 14:40:32 IST 2020
[cplayer] FFmpeg library versions:
[cplayer]    libavutil       56.46.100
[cplayer]    libavcodec      58.84.100
[cplayer]    libavformat     58.43.100
[cplayer]    libswscale      5.6.101
[cplayer]    libavfilter     7.81.100
[cplayer]    libswresample   3.6.100
[cplayer] FFmpeg version: N-97830-gb707abf091
[cplayer] 
[cplayer] Configuration: ./waf configure
[cplayer] List of enabled features: alsa asm build-date cplayer cplugins cuda-hwaccel cuda-interop debug-build drm egl egl-drm egl-helpers egl-x11 ffmpeg ffnvcodec gbm gbm.h gl gl-x11 glibc-thread-name glob glob-posix gpl iconv jpeg libass libavdevice libdl libm librt linux-fstatfs optimize posix posix-or-mingw pthreads pulse stdatomic vt.h x11 xv zlib
[cplayer] Setting option 'v' = '' (flags = 8)

[cplayer] Error parsing option osc (option not found)
[cplayer] Setting commandline option --osc=yes failed.
[cplayer] Exiting... (Fatal error)
```
How to build using lua support?

**Comment by Akemi** [comment]
install a supported lua version and make sure configure finds it.

**Comment by phanirithvij** [comment]
How to make sure the configure finds it?
What is the command? Please understand that people who ask these kind of questions don't know much about make, configure etc.

I didn't ignore any issue template. I clicked new issue and GitHub didn't open any issue template.

**Comment by Akemi** [comment]
you install lua (and possible dev packages) and configure will find it when a .pc file was created and can be found in your PKG_CONFIG_PATH. you can test with `pkg-config --libs --cflags 'lua'` (you can test with the strings here https://github.com/mpv-player/mpv/blob/102a083171478c69a8d2dd7de7c40d7687a9e809/waftools/checks/custom.py#L62-L70)
there is no command specific in mpv's build system. anything that can be done is usual linux stuff, like defining/extending a PKG_CONFIG_PATH env.
yes you can just follow the official build instructions. this repo is just for people that don't want to use their system provided ffmpeg and/or libass. otherwise it's basically the same. you don't need to know anything about configure/make etc besides calling the commands.
yes i already removed my comment about the template. no need to get hung up on it.
i am closing this because you didn't provide any kind of crucial information (i am just being as lazy as you), like maybe the build output or even your OS, that we can work with. why post the output of the mpv binary if you clearly have build problem?
if someone else has the same problem, which he can't really know since you didn't really provided any kind of meaningful info, it's most likely only a similar problem and he can just open another issue.

**Comment by CounterPillow** [comment]
Just to add some more info, it's important that mpv will only pick up Lua 5.1, Lua 5.2 or LuaJIT. Lua 5.3 will not work. I recommend you install LuaJIT (and its dev package, if your distribution has dev packages) from your distribution's package manager. Your distro package manager will install it in a way where mpv's build system will pick it up automatically.

**Comment by Flurrywinde** [comment]
I found my way here trying to get mpv to compile with lua support as well, so hopefully it'll help other people in the future to share my experience. I saw in other issues as well as here that what worked is installing luajit, but that wasn't enough.

I'm on Ubuntu 20.04.1.

I did `sudo apt install luajit`, compiled, and my lua scripts still didn't work.

Then, I did `sudo apt install libluajit-5.1-dev`.

At this point, I did as @Akemi above said: `pkg-config --libs --cflags 'lua'`, and it said lua was not found. Maybe, if I compiled at this point, it would have worked, but I assumed if that pkg-config command came up empty I was still missing something.

Thus, I did `sudo apt install liblua5.1-0-dev liblua5.1-0` also. `pkg-config` still came up empty, but I compiled anyway. And it worked.

I suspect the pkg-config command needs to be either `pkg-config --libs --cflags 'luajit'` or `pkg-config --libs --cflags 'lua5.1'` or some such, depending on which lua you installed.

To look for any lua, this seems to work: `pkg-config --list-all | grep -i lua`

**Comment by avih** [comment]
Lua is installed differently across distributions, and the package name is usually not "lua" alone. It can be `luajit` or `lua-52` or `lua-5.2` or several others, and mpv tries them all. See https://github.com/mpv-player/mpv/blob/master/waftools/checks/custom.py#L60

So you need to install the development files of one of the supported lua versions (luajit, lua 5.2, or lua 5.1), and mpv should find it.

Regardless, it's completely outside the scope of mpv-build. mpv-build only handles ffmpeg and libass - which are sometimes out of date by the distro. All the other libraries which mpv uses (a lot, including lua) are not built by mpv-build, and the build process of mpv itself looks for them when `./waf configure` is invoked..

**Comment by Flurrywinde** [comment]
Thanks, @avih . Even if this is outside the scope of mpv-build, do you think it'd be good to put lua in the list of essential dependencies? It is, after all, essential to mpv's ability to run lua scripts, similar to how the encoder libraries are outside the scope but also essential dependencies. Would a PR adding this to the readme be welcome?
