### ISSUE TITLE
--enable-libmpv-shared in mpv_options not working

### ISSUE THREAD

**Issue by ozmartian** [mpv-player/mpv-build#134]
Maybe i am doing something wrong but I only noticed recently that libmpv.so was no longer building using my mpv-build stack of scripts. Hasn't worked for a month or two now. Thx for all your work and help throughout the years guys!

this is when using mpv-master. release seems to work fine last time i checked. thx!

**Comment by aerdnar** [comment]
`--enable-libmpv-shared` depends on ffmpeg_options and /mpv_build/mpv/build/config.log can help. 
For example on raspbian there is some bug with `echo --enable-mmal >> ffmpeg_options` in 0.32.0 release due to /mpv_build/ffmpeg/libavcodec/libavcodec.pc which not include this flag `-L/opt/vc/lib` in Libs.private (you can edit it and launch ./build again not ./rebuild or maybe `export LDFLAGS='-L/opt/vc/lib'`) and /mpv/wscript cannot find -lmmal* library (that was my case) when it checks ffmpeg/libav by compiling a file with /mpv_build/ffmpeg/libavcodec/libavcodec.pc/Libs.private flags as you can see here:
https://github.com/mpv-player/mpv/commit/7d11eda72e90d7aa9df25127bd810aa7b191029c#diff-b79856260b3cc9b3e958c83a55bae1e46e31d232125b925c581022786a7bc042L479 row #479
It's should be fixed now in mpv/master because they removed libav compatibility and changed the way to test it.
That's bug is not related with your but maybe can help someone.

**Comment by ozmartian** [comment]
checked /mpv_build/mpv/build/config.log and see the following:

`Checking for OpenGL without platform-specific code (e.g. for libmpv)
libmpv-shared not found`

my mpv_options are:

`--prefix=/usr/local
--disable-static-build
--enable-libmpv-shared
--disable-oss-audio
--disable-alsa
--disable-debug-build
--enable-cplugins`

i even tried forcing --enable-libmpv-shared in scripts/mpv-config but no luck :-(

**Comment by ozmartian** [comment]
did some more testing and got it working by manually building from ./mpv/ folder passing the option on the command line. seems to be ignored from my mpv_options file for some reason.

```
./waf --enable-libmpv-shared configure
./waf --enable-libmpv-shared install
```
not sure why it ain't working as it should though

**Comment by Dudemanguy** [comment]
waf support no longer exists of course but `-Dlibmpv=true` in `mpv_options` should work.
