### ISSUE TITLE
Build fails with: undefined reference to symbol 'FcFontSetCreate'

### ISSUE THREAD

**Issue by realnc** [mpv-player/mpv-build#159]
Doing `./rebuild -j16` fails when building ffmpeg:

```none
INSTALL libavcodec/libavcodec.a
/usr/lib/gcc/x86_64-pc-linux-gnu/10.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: /home/realnc/projects/misc/mpv-build/build_libs/lib/libass.a(ass_fontconfig.o): undefined reference to symbol 'FcFontSetCreate'
/usr/lib/gcc/x86_64-pc-linux-gnu/10.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: /usr/lib64/libfontconfig.so.1: error adding symbols: DSO missing from command line
/usr/lib/gcc/x86_64-pc-linux-gnu/10.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: /home/realnc/projects/misc/mpv-build/build_libs/lib/libass.a(ass_fontconfig.o): undefined reference to symbol 'FcFontSetCreate'
/usr/lib/gcc/x86_64-pc-linux-gnu/10.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: /usr/lib64/libfontconfig.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
```

**Comment by avih** [comment]
Looks like you either don't have the fontconfig development files, or they're too old. They're required for libass.

**Comment by realnc** [comment]
> Looks like you either don't have the fontconfig development files, or they're too old. They're required for libass.

I have the latest version installed (2.13.1). This is on Gentoo. pkg-config says:

```
 $ pkg-config --libs fontconfig
-lfontconfig -lfreetype
```

**Comment by avih** [comment]
Did you update mpv-build? does your mpv-build includes this commit? https://github.com/mpv-player/mpv-build/commit/af71eb6d5e1ff77d8f9ae9195312603ced5c5d87

**Comment by realnc** [comment]
Looks like it's something in my `ffmpeg_options` file that causes this. I have quite a few flags in there. Strange that it is affecting libass though.

Will need to check them one by one to see which one causes the issue.

**Comment by avih** [comment]
If you build the ffmpeg binary, and ffmpeg needs libass - which needs fontconfig, then you might need to add the same LDFLAGS manualy when building ffmpeg. The issue was caused by a change in libass - which now also requires hardbuzz, but they also changed their pkgconfig file, so you might need to add the flags manually.

**Comment by realnc** [comment]
Right. It was `--enable-libass` that causes it. Builds fine without it.

**Comment by avih** [comment]
> What do I lose though without libass support? Do subtitles still work as intended?

In mpv - a lot. Subtitles and OSD and OSC (in fact, IIRC you can't disable libass in mpv anymore).

In ffmpeg - I don't know. mpv doesn't need ffmpeg built with libass because mpv uses libass directly, but I'm guessing the ffmpeg binary can make use of libass for some subtitles stuff during conversion etc.

**Comment by realnc** [comment]
Thanks. Will see if something seems off.

I suppose it's not possible to use the system-installed libass instead of the one bundled in mpv-build? That one would have no such issues.

**Comment by avih** [comment]
> I suppose it's not possible to use the system-installed libass

It's possible, and same for ffmpeg.

The whole point of mpv-build is that it builds latest versions of libass and ffmpeg and links mpv with them statically - so that it doesn't depend on possibly older versions of them system wide.

If your system libs are up to date, just go to the mpv source dir and run `./waf configure && ./waf build` and it will use the system libs.

**Comment by avih** [comment]
One thing you should keep in mind though is that sometimes ffmpeg is not compatible between versions - and mpv refuses to run if it was linked with one ffmpeg version while the (dynamic) system ffmpeg lib is a different version.

If you can ensure to rebuild mpv whenever your system ffmpeg is updated, then you'd have no issue and you don't need mpv-build at all.
