### ISSUE TITLE
Download/extract release archives instead of git cloning

### ISSUE THREAD

**Issue by postmodern** [mpv-player/mpv-build#63]
If the user wishes to build from the latest stable releases, perhaps the script could download the .tar.gz/.tar.bz2/.zip archives and extract them. This would be much faster than `git clone`.

**Comment by wm4** [comment]
The whole problem is actually writing a script for this.

**Comment by nerdouille** [comment]
Any news on this? I'd like to be able to use this script to build 0.17 stable, thanks

**Comment by Jimmy-Z** [comment]
a mere --depth=1 after git clone would suffice

**Comment by wm4** [comment]
> a mere --depth=1 after git clone would suffice

No, because we want to fetch all refs to pick the correct version. Unless you say --depth works with fetch.

**Comment by kevmitch** [comment]
We could start with a `--depth=1` clone and only convert it with `--unshallow` (git 1.8.3) when in `--release` mode.

**Comment by mrkapqa** [comment]
hello ,

i would also need to download a release -1 

not the latest 0.25 , but -1 , because that seemed still to work on my computer.

     ./use-mpv-release (-1) 

?

thank you so much

**Comment by kevmitch** [comment]
@mrkapqa this has nothing to do with this issue. 

Just git checkout the release you want.

    (cd mpv && git checkout v0.2.4)

Open a new issue or stick with the one you've already been using if there are further questions.

**Comment by avih** [comment]
> If the user wishes to build from the latest stable releases, perhaps the script could download the .tar.gz/.tar.bz2/.zip archives and extract them. This would be much faster than git clone.

While it is possible to download tarballs instead of using git, it's a whole lot of headache to script it and support it correctly. Just to name few issues:
- Get the correct file name to download.
- Whether or not to automate "get latest/release" tarballs and construct the URLs.
- Know the directory structure after extraction (for instance for ffmpeg it could be different top dir depending on the tarball source/type).
- And more.

In general the mpv-build scripts do two main things:
- The `update` script (which is affected by the use-foo-bar scripts) which is responsible to update the git repos, find and checkout the correct tag/branch, etc.
- The `build` script which just builds whatever exists at the ffmpeg/libass/mpv dirs.

So you can easily just create those three dirs yourself and in them put whatever versions of extracted tarballs you want and then run `./build`.

Using and/or fetching tarballs is, IMHO, out of scope currently for mpv-build.

> Any news on this? I'd like to be able to use this script to build 0.17 stable, thanks

See above. Just get whatever tarballs you want and extract them to libass/ffmpeg/mpv dirs and run `./build`.

> i would also need to download a release -1

This is not possible, but a recent addition allows doing for instance `./use-mpv-custom v0.25.0` which will use any branch/tag you want. Same goes for `use-ffmpeg-custom` and `use-libass-custom` - just choose your tags and then run `./update && ./rebuild`.

Note that the exact way to set these custom tags might change in the future, but for now, these work.
